export interface IPokemonData {
  id: string;
  type: PokemonType[];
  name: string;
  avatar: string;
  imageSrc: string;
  description: string;
  stats: IPokemonPhysicalStats;
  powerLevel: PowerLevelType;
  isOwned: boolean;
  hp: number;
  px: number;
  abilities: string[];
}

export interface IPokemonPhysicalStats {
  height: number;
  weight: number;
}

export enum PowerLevelType {
  "Power Level 1" = 1,
  "Power Level 2" = 2,
  "Power Level 3" = 3,
  "Power Level 4" = 4,
  "Power Level 5" = 5,
}

export type PokemonType =
  | "Normal"
  | "Fire"
  | "Water"
  | "Electric"
  | "Grass"
  | "Ice"
  | "Fighting"
  | "Poison"
  | "Ground"
  | "Flying"
  | "Psychic"
  | "Bug"
  | "Rock"
  | "Ghost"
  | "Dragon"
  | "Dark"
  | "Steel"
  | "Fairy";

export const typeAdvantages: {
  [key in PokemonType]: { [key in PokemonType]?: number };
} = {
  Normal: { Rock: 0.5, Ghost: 0, Steel: 0.5 },
  Fire: {
    Fire: 0.5,
    Water: 0.5,
    Grass: 2,
    Ice: 2,
    Bug: 2,
    Rock: 0.5,
    Dragon: 0.5,
    Steel: 2,
    Fairy: 1,
    Electric: 1,
    Fighting: 1,
    Poison: 1,
    Ground: 1,
    Flying: 1,
    Psychic: 1,
    Ghost: 1,
    Dark: 1,
  },
  Water: {
    Fire: 2,
    Water: 0.5,
    Grass: 0.5,
    Ground: 2,
    Rock: 2,
    Dragon: 0.5,
    Steel: 1,
    Fairy: 1,
    Electric: 1,
    Ice: 1,
    Bug: 1,
    Fighting: 1,
    Poison: 1,
    Flying: 1,
    Psychic: 1,
    Ghost: 1,
    Dark: 1,
  },
  Electric: {
    Water: 2,
    Electric: 0.5,
    Grass: 0.5,
    Ground: 0,
    Flying: 2,
    Dragon: 0.5,
    Steel: 1,
    Fairy: 1,
    Fire: 1,
    Ice: 1,
    Bug: 1,
    Rock: 1,
    Fighting: 1,
    Poison: 1,
    Psychic: 1,
    Ghost: 1,
    Dark: 1,
  },
  Grass: {
    Fire: 0.5,
    Water: 2,
    Grass: 0.5,
    Poison: 0.5,
    Ground: 2,
    Flying: 0.5,
    Bug: 0.5,
    Rock: 2,
    Dragon: 0.5,
    Steel: 0.5,
    Fairy: 1,
    Electric: 1,
    Ice: 1,
    Fighting: 1,
    Psychic: 1,
    Ghost: 1,
    Dark: 1,
  },
  Ice: {
    Fire: 0.5,
    Water: 0.5,
    Grass: 2,
    Ice: 0.5,
    Ground: 2,
    Flying: 2,
    Dragon: 2,
    Steel: 0.5,
    Fairy: 1,
    Electric: 1,
    Bug: 1,
    Rock: 1,
    Fighting: 1,
    Poison: 1,
    Psychic: 1,
    Ghost: 1,
    Dark: 1,
  },
  Fighting: {
    Normal: 2,
    Ice: 2,
    Rock: 2,
    Dark: 2,
    Steel: 2,
    Poison: 0.5,
    Flying: 0.5,
    Psychic: 0.5,
    Bug: 0.5,
    Fairy: 0.5,
    Ghost: 0,
    Fire: 1,
    Water: 1,
    Grass: 1,
    Electric: 1,
    Ground: 1,
    Dragon: 1,
  },
  Poison: {
    Grass: 2,
    Poison: 0.5,
    Ground: 0.5,
    Rock: 0.5,
    Ghost: 0.5,
    Steel: 0,
    Fairy: 2,
    Fire: 1,
    Water: 1,
    Electric: 1,
    Ice: 1,
    Flying: 1,
    Psychic: 1,
    Bug: 1,
    Dragon: 1,
    Dark: 1,
  },
  Ground: {
    Fire: 2,
    Electric: 2,
    Grass: 0.5,
    Poison: 2,
    Flying: 0,
    Bug: 0.5,
    Rock: 2,
    Steel: 2,
    Water: 1,
    Ground: 1,
    Ice: 1,
    Fighting: 1,
    Psychic: 1,
    Ghost: 1,
    Dragon: 1,
    Dark: 1,
    Fairy: 1,
  },
  Flying: {
    Grass: 2,
    Electric: 0.5,
    Fighting: 2,
    Bug: 2,
    Rock: 0.5,
    Steel: 0.5,
    Fairy: 1,
    Fire: 1,
    Water: 1,
    Ice: 1,
    Ground: 1,
    Psychic: 1,
    Ghost: 1,
    Dragon: 1,
    Dark: 1,
  },
  Psychic: {
    Fighting: 2,
    Poison: 2,
    Psychic: 0.5,
    Dark: 0,
    Steel: 0.5,
    Fire: 1,
    Water: 1,
    Grass: 1,
    Electric: 1,
    Ice: 1,
    Ground: 1,
    Flying: 1,
    Bug: 1,
    Rock: 1,
    Ghost: 1,
    Dragon: 1,
    Fairy: 1,
  },
  Bug: {
    Grass: 2,
    Psychic: 2,
    Dark: 2,
    Fire: 0.5,
    Fighting: 0.5,
    Poison: 0.5,
    Flying: 0.5,
    Ghost: 0.5,
    Steel: 0.5,
    Fairy: 0.5,
    Water: 1,
    Electric: 1,
    Ice: 1,
    Ground: 1,
    Rock: 1,
    Dragon: 1,
  },
  Rock: {
    Fire: 2,
    Ice: 2,
    Flying: 2,
    Bug: 2,
    Fighting: 0.5,
    Ground: 0.5,
    Steel: 0.5,
    Water: 1,
    Grass: 1,
    Electric: 1,
    Psychic: 1,
    Ghost: 1,
    Dark: 1,
    Dragon: 1,
    Fairy: 1,
  },
  Ghost: {
    Psychic: 2,
    Ghost: 2,
    Dark: 0.5,
    Normal: 0,
    Steel: 1,
    Fire: 1,
    Water: 1,
    Grass: 1,
    Electric: 1,
    Ice: 1,
    Fighting: 1,
    Poison: 1,
    Ground: 1,
    Flying: 1,
    Bug: 1,
    Rock: 1,
    Dragon: 1,
    Fairy: 1,
  },
  Dragon: {
    Dragon: 2,
    Steel: 0.5,
    Fairy: 0,
    Fire: 1,
    Water: 1,
    Grass: 1,
    Electric: 1,
    Ice: 1,
    Fighting: 1,
    Poison: 1,
    Ground: 1,
    Flying: 1,
    Psychic: 1,
    Bug: 1,
    Rock: 1,
    Ghost: 1,
    Dark: 1,
  },
  Dark: {
    Psychic: 2,
    Ghost: 2,
    Fighting: 0.5,
    Dark: 0.5,
    Fairy: 0.5,
    Fire: 1,
    Water: 1,
    Grass: 1,
    Electric: 1,
    Ice: 1,
    Ground: 1,
    Flying: 1,
    Poison: 1,
    Rock: 1,
    Dragon: 1,
    Bug: 1,
  },
  Steel: {
    Fairy: 2,
    Ice: 2,
    Rock: 2,
    Fire: 0.5,
    Water: 0.5,
    Electric: 0.5,
    Steel: 0.5,
    Fighting: 1,
    Poison: 1,
    Ground: 1,
    Flying: 1,
    Psychic: 1,
    Bug: 1,
    Ghost: 1,
    Dark: 1,
    Dragon: 1,
  },
  Fairy: {
    Fighting: 2,
    Dragon: 2,
    Dark: 2,
    Fire: 0.5,
    Poison: 0.5,
    Steel: 0.5,
    Water: 1,
    Grass: 1,
    Electric: 1,
    Ice: 1,
    Ground: 1,
    Flying: 1,
    Psychic: 1,
    Bug: 1,
    Rock: 1,
    Ghost: 1,
  },
};
